# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d95a5bf58fab8056452a721f34fb8783baf49c3f2e152b100bc63c229333b3b224cd97842381aef65a10c8a38ee8766e1531085623483223dde0ede5c38276d3

test:
  secret_key_base: f5d0bc3eb3142b50305b4adb87a6a8e00a97a2f0381d104bbd7c808c8df32cce87620292c3f6f107681a40ccb1cc4dc77550627eabfc8f6e9beb0ef0c1ece60c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
